### ISSUE TITLE
ImportError: cannot import name 'get_current_traceback' from 'werkzeug.debug.tbtools'

### ISSUE THREAD

**Issue by kjspring** [learn-co-curriculum/dsc-dash-intro#1]
## Link to Canvas

https://learning.flatironschool.com/courses/5318/pages/introduction-to-dash?module_item_id=423140

## Issue Subtype

- [x] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```
1 # import jupyter notebook version of dash framework
----> 2 from jupyter_dash import JupyterDash as Dash
      3 # import html elements for dash
      4 from dash import html

File D:\ProgramData\Anaconda3\envs\dash-env\lib\site-packages\jupyter_dash\__init__.py:2, in <module>
      1 import jupyter_dash.comms
----> 2 from .jupyter_app import JupyterDash
      3 from .version import __version__
      5 def _jupyter_nbextension_paths():

File D:\ProgramData\Anaconda3\envs\dash-env\lib\site-packages\jupyter_dash\jupyter_app.py:21, in <module>
     17 from ansi2html import Ansi2HTMLConverter
     18 import uuid
---> 21 from werkzeug.debug.tbtools import get_current_traceback
     23 from .comms import _dash_comm, _jupyter_config, _request_jupyter_config
     26 class JupyterDash(dash.Dash):

ImportError: cannot import name 'get_current_traceback' from 'werkzeug.debug.tbtools'
```

### Concern

There is a dependency issue. 'get_current_traceback' has been changed to the class DebugTraceback

## (Optional) Proposed Solution

Solution here:
https://github.com/plotly/dash/issues/1992

I had to go into jupyter_app.py and change:
```
from werkzeug.debut.tbtools import get_current_traceback
```
to
```
from werkzeug.debug.tbtools import DebugTraceback
```

## What OS Are You Using?

- [ ] OS X
- [x] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

**Comment by noble-g** [comment]
hi kjspring,

please how did you go into the jupyter_app.py to change the code you changed.
I'm also facing a similar problem

**Comment by jessepisel** [comment]
thanks for opening this issue 👋 . I have updated the install instructions with commit [fe5cee8](https://github.com/learn-co-curriculum/dsc-dash-intro/commit/fe5cee8e5635f3f4c9d44b829065c896a0ad7e16). Following the install instructions with the updated packages resolves this issue, so I am closing this issue at this time.
